### PR TITLE
feat: add MeshGateway resources

### LINKED ISSUE #28: Add builtin gateway in the demo
### Description

The builtin gateway is here. It would be great to have it running in the demo

### PR DESCRIPTION
**Pull request by michaelbeaumont**
Add resources and update README.

Closes #28

### CODE REVIEW

**Review by lahabana — COMMENTED** [review]
Why have it as a separate file rather than just inside the existing app.yaml?

**Comment by michaelbeaumont** [comment]
Because it's easier to do `--without-gateway` in `install demo` :grinning:

**Comment by michaelbeaumont** [comment]
But also of note, adding these resources to `app.yaml` makes it impossible to deploy the demo-app without Kuma.

**Comment by lahabana** [comment]
Ok sounds good then :)

**Review by lahabana — APPROVED** [review]

**Pull request merged**
