### PR TITLE
Updated URL to kuma-counter-demo

### PR DESCRIPTION
**Pull request by d19dotca**
Old URL: https://github.com/subnetmarco/kuma-demo/
New URL: https://github.com/kumahq/kuma-counter-demo

Signed-off-by: Dustin Dauncey <dustin.dauncey@konghq.com>

### CODE REVIEW

**Review by subnetmarco — APPROVED** [review]

**Comment by subnetmarco** [comment]
Good catch!

**Review by d19dotca — COMMENTED** [review]
Signed-off-by: Dustin Dauncey dustin.dauncey@konghq.com

**Comment by d19dotca** [comment]
Evidently I'm struggling with this DCO thing. 😅  I'll get it though.

**Comment by jpeach** [comment]
> Evidently I'm struggling with this DCO thing. sweat_smile I'll get it though.

Hey @d19dotca , you need to sign the commits using the `git commit -s` flag. You will need to add the signoff to the existing commits (using the --amend flag). Happy to help you thought the process if you want, just ping me on the Kuma slack.

**Comment by d19dotca** [comment]
Thanks for the help on the DCO, James! :-)

**Pull request merged**
